config/routes.rb
Rails.application.routes.draw do
  resources :devices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/notification/notify' => 'notification#notify'

  resources :notification do
    get :dashboard
  end

  root 'notification#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:model, :uuid, :token, :platform)
    end
end

app/controllers/notification_controller.rb
class NotificationController < ApplicationController
  def dashboard

  end
  def notify
        #get all devices registered in our db and loop through each of them
    Device.all.each do |device|
      n = Rpush::Gcm::Notification.new
            # use the pushme_droid app we previously registered in our initializer file to send the notification
      n.app = Rpush::Gcm::App.find_by_name("pushme")
      n.registration_ids = [device.token]

            # parameter for the notification
      n.notification = {
        body: 'This is the notification body . . .!',
           	title: 'Hey this is notification title!',
           	sound: 'default'
       	}
            #save notification entry in the db
      n.save!
    end

        # send all notifications stored in db
        Rpush.push

    render json: {sent: true}, status: :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_with(model: device, local: true) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :uuid %>
    <%= form.text_field :uuid %>
  </div>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_area :token %>
  </div>

  <div class="field">
    <%= form.label :platform %>
    <%= form.text_field :platform %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Uuid</th>
      <th>Token</th>
      <th>Platform</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.model %></td>
        <td><%= device.uuid %></td>
        <td><%= device.token %></td>
        <td><%= device.platform %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @device.model %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @device.uuid %>
</p>

<p>
  <strong>Token:</strong>
  <%= @device.token %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @device.platform %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pushme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notification/dashboard.html.erb
Welcome to pushme app!

hit to '/notification/notify'